blueprint:
  name: GoodWe & Tibber Smart Charge (v5.8 Final Fix)
  description: |
    **Intelligente Batteriesteuerung für GoodWe Wechselrichter mit Tibber**
    
    Dieses Blueprint optimiert deinen Speicher vollautomatisch, um Stromkosten zu senken und den Eigenverbrauch zu maximieren.

    **Funktionsweise:**
    1. **Günstiges Laden:** Der Akku wird in den **X günstigsten Stunden** des Tages (basierend auf Tibber-Preisen für heute & morgen) aus dem Netz geladen (Modus: Backup).
    2. **Intelligente Zurückhaltung:** Wenn für die günstigen Stunden genug **Solarstrom vorhergesagt** ist (über optionalen Forecast-Sensor) oder aktuell die Sonne scheint, wird das Netzladen übersprungen.
    3. **Export-Management:** Im Eigenverbrauchsmodus (General) wird die **Exportsperre** automatisch aktiviert, wenn der Akku entladen wird, und deaktiviert, wenn der Akku voll ist.

    **Status-Helfer:**
    Der Blueprint benötigt zwei existierende Helfer:
    * **Text-Helfer (`input_text`)**: Zeigt die Uhrzeiten der günstigsten Ladestunden an.
    * **Toggle-Helfer (`input_boolean`)**: Zeigt an, ob der Akku aktuell aus dem Netz geladen wird.

    **Voraussetzungen:**
    * **HACS GoodWe Integration**
    * **Tibber Daten-Sensor** (manuell in configuration.yaml erstellt, siehe Anleitung)

  domain: automation
  input:
    tibber_price_data_sensor:
      name: Tibber Preisdaten Sensor (Verarbeitet)
      description: >
        Der vorbereitete Template-Sensor, der die Tibber-Preisdaten als Attribut 'tibber_data' enthält
        (z.B. sensor.tibber_processed_prices aus der configuration.yaml).
      selector:
        entity:
          domain: sensor
    pv_power_sensor:
      name: Aktuelle PV-Leistung (W)
      description: Sensor für die aktuelle Erzeugung des Wechselrichters.
      selector:
        entity:
          domain: sensor
          device_class: power
    battery_soc_sensor:
      name: Batterie Ladestand (%)
      description: Sensor für den aktuellen SOC der Batterie.
      selector:
        entity:
          domain: sensor
          device_class: battery
    goodwe_work_mode_selector:
      name: GoodWe Betriebsmodus Selector
      description: >
        Die Entität zum Umschalten des Modus (z.B. select.goodwe_work_mode).
        Muss Optionen wie 'General' und 'Backup' haben.
      selector:
        entity:
          domain: select
    goodwe_export_limit_switch:
      name: GoodWe Exportsperre Schalter
      description: >
        Der Schalter zum Ein-/Ausschalten der Einspeisebegrenzung.
      selector:
        entity:
          domain: switch
    solar_forecast_sensor:
      name: Solar Prognose Sensor (Optional)
      description: >
        Ein Sensor, der die erwartete Solarleistung in Watt liefert.
      default: null
      selector:
        entity:
          domain: sensor
    charge_hours:
      name: Ladedauer in Stunden
      description: Anzahl der günstigsten Stunden, in denen geladen werden soll.
      default: 3
      selector:
        number:
          min: 1
          max: 8
          unit_of_measurement: "Stunden"
    pv_threshold_low:
      name: PV-Schwellenwert Niedrig (W)
      description: Unterhalb dieses Wertes gilt - Keine nennenswerte Sonne.
      default: 50
      selector:
        number:
          min: 0
          unit_of_measurement: "W"
    pv_threshold_high:
      name: PV-Schwellenwert Hoch (W)
      description: Oberhalb dieses Wertes gilt - Viel Überschuss.
      default: 50
      selector:
        number:
          min: 0
          unit_of_measurement: "W"
    soc_full_threshold:
      name: Batterie Voll-Schwellenwert (%)
      description: Ab diesem Ladestand gilt der Akku als voll.
      default: 99
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"
    helper_cheapest_hours_text:
      name: Text-Helfer Günstige Stunden
      description: >
        Ein input_text-Helfer, der die günstigsten Ladestunden anzeigt.
        Du musst diesen Helfer vorher in Home Assistant erstellen (Einstellungen > Geräte & Dienste > Helfer).
      selector:
        entity:
          domain: input_text
    helper_charging_from_grid_toggle:
      name: Toggle-Helfer Akku lädt aus Netz
      description: >
        Ein input_boolean-Helfer, der anzeigt, ob der Akku gerade aus dem Netz geladen wird.
        Du musst diesen Helfer vorher in Home Assistant erstellen (Einstellungen > Geräte & Dienste > Helfer).
      selector:
        entity:
          domain: input_boolean

mode: single
max_exceeded: silent

trigger:
  - platform: time_pattern
    minutes: "*"
  - platform: state
    entity_id:
      - !input pv_power_sensor
      - !input battery_soc_sensor
